name: code-review
description: Comprehensive code review workflow with security and performance analysis
version: "1.0"

config_source: "config/stack.yaml"

metadata:
  icon: "🔍"
  estimated_time: "15-30 minutes"
  complexity: "simple-to-moderate"

variables:
  review_scope: "{user_input}"
  output_folder: "_output/reviews"

phases:
  - phase: 1
    name: "Analysis"
    parallel: true
    agents:
      - code-reviewer
      - security-reviewer
    checkpoint: false

  - phase: 2
    name: "Deep Analysis (if needed)"
    parallel: false
    conditional: "issues_found"
    agents:
      - performance-optimizer
    checkpoint: false

  - phase: 3
    name: "Report"
    parallel: false
    agents:
      - code-reviewer
    checkpoint: true
    checkpoint_reason: "Review findings before generating report"

instructions_path: "./steps"

steps:
  - id: "step-01"
    file: "step-01-scope.md"
    name: "Define Review Scope"
    required: true

  - id: "step-02"
    file: "step-02-code-quality.md"
    name: "Code Quality Review"
    required: true

  - id: "step-03"
    file: "step-03-security.md"
    name: "Security Review"
    required: true

  - id: "step-04"
    file: "step-04-report.md"
    name: "Generate Report"
    required: true

output:
  template: "./review-output.template.md"
  default_path: "{output_folder}/review-{date}.md"
